version: '3.8'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: api
    # env_file:
    #   - .env
    volumes:
      - ./backend/:/code/
    ports:
      - "8003:8003"
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
       - ./client/src:/code/src
    depends_on:
      - api