services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: api
    env_file:
      - .env
    volumes:
      - ./backend/:/code/
    ports:
      - "8003:8003"
    depends_on:
      - db

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
       - ./client/src:/code/src
    depends_on:
      - api

  pgadmin:
    image: dpage/pgadmin4
    container_name: japanese_pgadmin 
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres-data: {}
  pgadmin: {}
   