"""update progress schema

Revision ID: 503b1fbb65ce
Revises: 9797ddda5e67
Create Date: 2024-10-08 10:25:00.792122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503b1fbb65ce'
down_revision: Union[str, None] = '9797ddda5e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card_progress', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint('user_card_progress_user_id_fkey', 'user_card_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_card_progress', 'users', ['username'], ['username'])
    op.drop_column('user_card_progress', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card_progress', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_card_progress', type_='foreignkey')
    op.create_foreign_key('user_card_progress_user_id_fkey', 'user_card_progress', 'users', ['user_id'], ['id'])
    op.drop_column('user_card_progress', 'username')
    # ### end Alembic commands ###
