"""update card

Revision ID: 9797ddda5e67
Revises: 8a7060461128
Create Date: 2024-09-28 03:43:10.526422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9797ddda5e67'
down_revision: Union[str, None] = '8a7060461128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'stroke_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'stroke_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
